Improve auto_analyse_raw_data and add lint/unit tests. * Make analyse script code unittest-able. * Improve raw data parsing for analyse script. * Add some unit tests for analyse script. * Update Makefile(s) to use 'run_tests' to run their tests. * Add python unit & lint tests into Travis

diff --git a/tools/Makefile b/tools/Makefile
--- a/tools/Makefile
+++ b/tools/Makefile
@@ -24,8 +24,20 @@ CXXFLAGS += -g -Wall -Wextra -pthread
 
 all : gc_decode
 
+run_tests : all
+	failed=""; \
+	for py_unittest in *_test.py; do \
+	  echo "RUNNING: $${py_unittest}"; \
+		python ./$${py_unittest} || failed="$${failed} $${py_unittest}"; \
+	done; \
+	if [ -n "$${failed}" ]; then \
+		echo "FAIL: :-( :-( Unit test(s)$${failed} failed! :-( :-("; exit 1; \
+	else \
+		echo "PASS: \o/ \o/ All unit tests passed. \o/ \o/"; \
+	fi
+
 clean :
-	rm -f  *.o gc_decode
+	rm -f  *.o *.pyc gc_decode
 
 
 # All the IR protocol object files.
